import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Button, CssBaseline, Stack, ThemeProvider } from "@mui/material";
import { createTheme } from "@mui/material/styles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const theme = createTheme({
  palette: {
    primary: {
      main: "#1976d2",
    },
    secondary: {
      main: "#dc004e",
    },
  },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center justify-between p-4 bg-gray-800 text-white">
          <div className="text-xl font-bold">
            <Link href="/" className="hover:text-gray-400">
              Awing-app
            </Link>
          </div>
          <div className="space-x-4">
            <Link href="/" className="hover:text-gray-400">
              Home
            </Link>
            <Link href="/cal" className="hover:text-gray-400">
              Calculator
            </Link>
            <Link href="/about" className="hover:text-gray-400">
              About
            </Link>
            <Link href="/contact" className="hover:text-gray-400">
              Contact
            </Link>
          </div>
        </nav>

        <AppRouterCacheProvider options={{ key: "css" }}>
          <div className="container mx-auto p-4 w-8/10">{children}</div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
